export const deliveryData = [
  {
    id: 1,
    orderId: 'ORD1001',
    name: 'Hotel Radha Krishna',
    customerName: 'Rohit Sharma',
    expectedEarnings: 20.0,
    timer: '30.00',
    paymentMode: 'Cash on Delivery',
    pickup: {
      label: 'Pickup From',
      address: 'Plot 5, Krishna Nagar, Sector 20, Near Omkar Building, Chinchwad, Pune.',
      latitude: 18.6275,
      longitude: 73.8001,
    },
    drop: {
      label: 'Drop To',
      address: 'Flat 12, Sai Residency, Aundh Road, Pune.',
      latitude: 18.6349,
      longitude: 73.8125,
    },
    contact: '9893451098',
    orderItems: [
      { itemName: 'Paneer Butter Masala', quantity: 1, price: 180, type: 'veg' },
      { itemName: '2 Butter Naan', quantity: 1, price: 60, type: 'veg' },
      { itemName: 'Jeera Rice', quantity: 1, price: 120, type: 'veg' },
    ],
    buttonLabel: 'PICK UP',
  },
  {
    id: 2,
    orderId: 'ORD1002',
    name: 'Sharma Ice Cream & Pavbhaji',
    customerName: 'Aditi Verma',
    expectedEarnings: 20.0,
    timer: '25.30',
    paymentMode: 'Cash on Delivery',
    pickup: {
      label: 'Pickup From',
      address: 'Shop 10, Balina Apartment, Sector 29, Ravet, Pune.',
      latitude: 18.6501,
      longitude: 73.7802,
    },
    drop: {
      label: 'Drop To',
      address: 'B-102, Akash Residency, Nigdi, Pune.',
      latitude: 18.6633,
      longitude: 73.7911,
    },
    contact: '9893451091',
    orderItems: [
      { itemName: 'Pav Bhaji', quantity: 2, price: 180, type: 'veg' },
      { itemName: 'Vanilla Ice Cream', quantity: 1, price: 60, type: 'veg' },
    ],
    buttonLabel: 'PICK UP',
  },
  {
    id: 3,
    orderId: 'ORD1003',
    name: 'Hyderabadi Spice Corner',
    customerName: 'Arjun Mehta',
    expectedEarnings: 25.0,
    timer: '28.45',
    paymentMode: 'Cash on Delivery',
    pickup: {
      label: 'Pickup From',
      address: 'Shop 22, Green Plaza, Baner, Pune.',
      latitude: 18.5577,
      longitude: 73.8079,
    },
    drop: {
      label: 'Drop To',
      address: 'Flat 5, Kunal Icon, Baner Pashan Link Road, Pune.',
      latitude: 18.5623,
      longitude: 73.8225,
    },
    contact: '9893476543',
    orderItems: [
      { itemName: 'Chicken Biryani', quantity: 1, price: 220, type: 'non-veg' },
      { itemName: 'Tandoori Chicken (Half)', quantity: 1, price: 190, type: 'non-veg' },
      { itemName: 'Coke (500ml)', quantity: 1, price: 40, type: 'veg' },
    ],
    buttonLabel: 'PICK UP',
  },
  {
    id: 4,
    orderId: 'ORD1004',
    name: 'Fish & Grill Express',
    customerName: 'Sneha Patil',
    expectedEarnings: 30.0,
    timer: '32.10',
    paymentMode: 'Cash on Delivery',
    pickup: {
      label: 'Pickup From',
      address: 'Plot 8, Blue Heaven Complex, Pimple Saudagar, Pune.',
      latitude: 18.5921,
      longitude: 73.7866,
    },
    drop: {
      label: 'Drop To',
      address: 'Flat 10, Paradise Towers, Rahatani, Pune.',
      latitude: 18.6033,
      longitude: 73.7922,
    },
    contact: '9893488822',
    orderItems: [
      { itemName: 'Grilled Fish with Lemon Butter', quantity: 1, price: 320, type: 'non-veg' },
      { itemName: 'Garlic Bread', quantity: 1, price: 80, type: 'veg' },
      { itemName: 'Cold Coffee', quantity: 1, price: 90, type: 'veg' },
    ],
    buttonLabel: 'PICK UP',
  },
];
